---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-creds
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  url: {{ .Values.giteaConfig.url }}
  token: {{ .Values.giteaConfig.token }}
